import type { Assignment, AssignmentSettings, Submission, ProcessMetrics, ProcessReport, TimelineEvent, DEFAULT_ASSIGNMENT_SETTINGS } from './types';

const baseSettings: AssignmentSettings = {
  paste_allowed: false,
  leave_and_return: false,
  multiple_sessions: false,
  student_can_view_report: false,
};

export const DEMO_ASSIGNMENTS: Assignment[] = [
  {
    id: 'assign-1',
    course_id: 'course-1',
    title: 'Analytical Essay on Modernist Poetry',
    description: 'Write a 1500–2000 word analytical essay examining the use of fragmentation in T.S. Eliot\'s The Waste Land.',
    instructions: `## Assignment Instructions\n\nWrite a **1500–2000 word analytical essay** examining the use of fragmentation in T.S. Eliot's *The Waste Land*.\n\n### Requirements\n\n1. Develop a clear thesis about Eliot's use of fragmentation as a literary device\n2. Analyze at least three specific passages from the text\n3. Connect your analysis to the broader modernist movement\n4. Use proper MLA citation format\n\n### Evaluation Criteria\n\n- Strength of thesis and argument\n- Close reading and textual evidence\n- Clarity and organization of prose\n- Writing process evidence (via Origyn report)`,
    due_date: '2026-04-15T23:59:00Z',
    settings: { ...baseSettings, student_can_view_report: true, min_word_count: 1500, max_word_count: 2000 },
    is_published: true,
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 'assign-2',
    course_id: 'course-1',
    title: 'Close Reading Response',
    description: 'A short in-class timed writing exercise analyzing a passage from Virginia Woolf.',
    instructions: '## Close Reading\n\nYou have **45 minutes** to write a close reading of the provided passage from *Mrs Dalloway*.\n\nFocus on Woolf\'s use of stream of consciousness and how it reveals character interiority.',
    due_date: '2026-04-08T15:00:00Z',
    settings: { ...baseSettings, time_limit_minutes: 45, paste_allowed: false },
    is_published: true,
    created_at: '2026-03-05T10:00:00Z',
    updated_at: '2026-03-05T10:00:00Z',
  },
  {
    id: 'assign-3',
    course_id: 'course-1',
    title: 'Research Proposal Draft',
    description: 'Submit a draft research proposal for your final paper.',
    instructions: '## Research Proposal\n\nSubmit a 500–800 word research proposal for your final paper.\n\nInclude:\n- Proposed topic and research question\n- Preliminary thesis\n- At least 3 potential sources\n- Brief methodology description',
    due_date: '2026-04-20T23:59:00Z',
    settings: { ...baseSettings, leave_and_return: true, multiple_sessions: true, student_can_view_report: true, min_word_count: 500, max_word_count: 800 },
    is_published: false,
    created_at: '2026-03-10T10:00:00Z',
    updated_at: '2026-03-10T10:00:00Z',
  },
];

const demoMetrics: ProcessMetrics = {
  session: {
    total_sessions: 1,
    total_elapsed_seconds: 4320,
    active_writing_seconds: 3180,
    idle_seconds: 1140,
    focus_blur_count: 4,
    exits_and_returns: 2,
    autosave_count: 12,
    session_continuity: 'high',
  },
  input: {
    typed_characters: 8420,
    pasted_characters: 340,
    paste_event_count: 2,
    paste_sizes: [180, 160],
    cut_count: 3,
    delete_count: 45,
    backspace_count: 312,
    insertion_bursts: 87,
    deletion_bursts: 24,
    avg_burst_length: 12,
    pause_count: 34,
    typed_vs_pasted_ratio: 0.96,
    paste_dependence: 'low',
  },
  revision: {
    edits_to_earlier_sections: 8,
    return_edits: 5,
    paragraph_rewrites: 2,
    revision_depth: 'medium',
    revision_density_over_time: [2, 5, 8, 12, 18, 22, 25, 28, 30, 32, 34, 35],
  },
  composition: {
    drafting_pattern: 'moderately_iterative',
    composition_order: ['intro', 'body-1', 'body-2', 'intro-revision', 'body-3', 'conclusion', 'body-2-revision'],
    revisited_earlier_paragraphs: true,
  },
};

const demoTimeline: TimelineEvent[] = [
  { timestamp: '2026-04-10T14:00:00Z', type: 'session_start', word_count: 0, label: 'Session started' },
  { timestamp: '2026-04-10T14:05:00Z', type: 'autosave', word_count: 85 },
  { timestamp: '2026-04-10T14:12:00Z', type: 'autosave', word_count: 240 },
  { timestamp: '2026-04-10T14:18:00Z', type: 'paste', word_count: 280, label: 'Pasted 180 chars' },
  { timestamp: '2026-04-10T14:20:00Z', type: 'blur', word_count: 310, label: 'Left editor' },
  { timestamp: '2026-04-10T14:22:00Z', type: 'focus', word_count: 310, label: 'Returned to editor' },
  { timestamp: '2026-04-10T14:30:00Z', type: 'autosave', word_count: 520 },
  { timestamp: '2026-04-10T14:40:00Z', type: 'autosave', word_count: 780 },
  { timestamp: '2026-04-10T14:48:00Z', type: 'autosave', word_count: 1020 },
  { timestamp: '2026-04-10T14:55:00Z', type: 'paste', word_count: 1060, label: 'Pasted 160 chars' },
  { timestamp: '2026-04-10T15:00:00Z', type: 'autosave', word_count: 1280 },
  { timestamp: '2026-04-10T15:08:00Z', type: 'autosave', word_count: 1450 },
  { timestamp: '2026-04-10T15:12:00Z', type: 'autosave', word_count: 1620 },
  { timestamp: '2026-04-10T15:12:30Z', type: 'session_end', word_count: 1620, label: 'Submitted' },
];

export const DEMO_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-1',
    assignment_id: 'assign-1',
    user_id: 'demo-student-1',
    content: `The Waste Land, published in 1922, stands as one of the most revolutionary poems of the twentieth century. T.S. Eliot's masterwork employs fragmentation not merely as a stylistic device but as a fundamental principle of composition that mirrors the shattered consciousness of post-war modernity.\n\nEliot's use of fragmentation operates on multiple levels simultaneously. At the surface level, the poem's five sections present a disjointed series of voices, images, and allusions that resist conventional narrative coherence. The opening lines of "The Burial of the Dead" immediately establish this principle: "April is the cruellest month, breeding / Lilacs out of the dead land." The pastoral convention is inverted, and the reader is plunged into a landscape where traditional meanings have been overturned.\n\nThe fragmentation deepens through Eliot's technique of juxtaposition. In "A Game of Chess," the ornate description of the upper-class woman's boudoir is set against the working-class pub conversation about Lil and her husband. These two scenes are not connected by narrative logic but by thematic resonance—both depict relationships drained of genuine communication and intimacy.\n\nPerhaps most significantly, Eliot's fragmentation extends to language itself. The poem incorporates passages in German, French, Italian, and Sanskrit, creating a babel of tongues that suggests both the cosmopolitan scope of Western culture and its ultimate inability to communicate coherent meaning. The famous closing lines—"Shantih shantih shantih"—reach beyond European languages entirely.\n\nThis multilingual fragmentation connects to the broader modernist project of questioning inherited forms. Where Victorian poetry maintained formal unity even when addressing themes of doubt and loss, Eliot's method insists that form must embody the crisis of meaning. The poem's fragments are not pieces of a puzzle that can be reassembled; they are evidence of an irreparable break.\n\nThe implications for literary criticism are significant. Reading The Waste Land demands a new kind of attention—one that accepts discontinuity as meaningful rather than seeking to resolve it. Eliot's fragmentation thus becomes not a failure of coherence but an achievement of honesty about the modern condition.`,
    word_count: 1620,
    status: 'submitted',
    submitted_at: '2026-04-10T15:12:30Z',
    created_at: '2026-04-10T14:00:00Z',
    updated_at: '2026-04-10T15:12:30Z',
    student_name: 'Alex Chen',
    student_email: 'achen@princeton.edu',
    metrics: demoMetrics,
  },
  {
    id: 'sub-2',
    assignment_id: 'assign-1',
    user_id: 'demo-student-2',
    content: '',
    word_count: 890,
    status: 'submitted',
    submitted_at: '2026-04-12T09:30:00Z',
    created_at: '2026-04-11T20:00:00Z',
    updated_at: '2026-04-12T09:30:00Z',
    student_name: 'Maya Patel',
    student_email: 'mpatel@princeton.edu',
    metrics: {
      ...demoMetrics,
      input: { ...demoMetrics.input, paste_dependence: 'medium', pasted_characters: 2100, typed_vs_pasted_ratio: 0.65 },
      revision: { ...demoMetrics.revision, revision_depth: 'low' },
      composition: { ...demoMetrics.composition, drafting_pattern: 'mostly_linear' },
    },
  },
  {
    id: 'sub-3',
    assignment_id: 'assign-1',
    user_id: 'demo-student-3',
    content: '',
    word_count: 1780,
    status: 'submitted',
    submitted_at: '2026-04-14T22:45:00Z',
    created_at: '2026-04-13T16:00:00Z',
    updated_at: '2026-04-14T22:45:00Z',
    student_name: 'James Wright',
    student_email: 'jwright@princeton.edu',
    metrics: {
      ...demoMetrics,
      session: { ...demoMetrics.session, session_continuity: 'low', focus_blur_count: 14, total_sessions: 3 },
      revision: { ...demoMetrics.revision, revision_depth: 'high', return_edits: 18 },
      composition: { ...demoMetrics.composition, drafting_pattern: 'highly_iterative' },
    },
  },
];

export const DEMO_REPORT: ProcessReport = {
  submission_id: 'sub-1',
  generated_at: new Date().toISOString(),
  metrics: demoMetrics,
  timeline: demoTimeline,
  summary_labels: {
    paste_dependence: 'Low paste dependence',
    revision_depth: 'Medium revision depth',
    drafting_pattern: 'Moderately iterative drafting',
    session_continuity: 'High session continuity',
  },
};
